### ISSUE TITLE
git-xet picks up incorrect profile for mount/clone command

### ISSUE THREAD

**Issue by sirahd** [xetdata/xet-core#107]
On commands that do not operate on existing xet repository (like clone/mount), git-xet does not use the profile associated to the repo URL and instead uses the default prod config.

For example, when testing git-xet command with local xetea, running `git-xet mount http://localhost:3000/<username>/<repo>.git` does not use the `[localhost3000]` profile in `~/.xetconfig` if there is one. The side effect of this is that this command will use prod config for username, token, PostHog token, etc. which is incorrect.

The potential fix is modifying the init function in https://github.com/xetdata/xet-core/blob/e2ddf177c634a7891a4d959a7ca6d10c1525c74c/rust/gitxetcore/src/command.rs#L301 to handle mount/clone in a special case to take config from the mount/clone URL

**Comment by seanses** [comment]
Is this with the latest git-xet?

**Comment by erinys** [comment]
Test again with the latest git-xet.

**Comment by sirahd** [comment]
Likely fixed in the latest git-xet since I cannot repro with the local git-xet built from latest main
