### ISSUE TITLE
Please add tags to this repository at the point of release

### ISSUE THREAD

**Issue by alerque** [xetdata/xet-core#132]
Trying to package `git-xet` and others for distros is a pain because there is no clear release point. I realize binaries are posted on the other repository along with release tags, but they are not reproducible nor do they always match system libraries and compile options. I am able to build Arch Linux packages just fine, but it is unclear what version they are. Typically I take the last commit in here before the version is bumped to the *next* release, but it isn't always clear if that is what is built and packaged as a release.

Please tag the source repository here with the tag at the point of building a release and posting binaries elsewhere.

**Comment by alerque** [comment]
Once again having to guess, I released 586264053b96f63a36550aabb4aaf9999e4f053c96dc5e52a1d9c2cffddfbd11 as 0.11.5 to Arch Linux. Please tag this repo when you cut releases. You can still use the GitHub Releases feature on the other repository to post binaries if you want, but a Git tag in the source is needed!

**Comment by alerque** [comment]
Still a problem. I'm guessing 1f2d3cece736664d155cf991fa952ebfc54d5eb2 for v0.12.0, but this repository still needs tags.

**Comment by alerque** [comment]
Guessing a2681c8b8dd6396a7128b7b3e4f176e5bf94860a for v0.12.1.

**Comment by alerque** [comment]
`$RANDOM` suggests I use 4ba4d135d03ea5d1c58b06993617c87032b1d9fe for v0.13.5.

**Comment by seanses** [comment]
Added tags since v0.11.0. Thank you!

**Comment by alerque** [comment]
Fantastic, thank you!

**Comment by alerque** [comment]
The [v0.12.6](https://github.com/xetdata/xet-tools/releases/tag/v0.12.6) release marked over on the issue stub repository did not get tagged here. I guess some port of the release workflow needs updating: whether that is automation or release documentation or whatever.

**Comment by seanses** [comment]
Tagging is not built into our automatic release workflow yet so there will be some delay for manual tagging.

**Comment by alerque** [comment]
Some delay is okay as long as it doesn't get overlooked. Is there a release checklist / workflow document of some kind that gets followed where it could be added, preferably even *before* the other stub repository gets a tag? That would make the most sense since having binary builds before the tag shows up is kind of strange.

**Comment by hoytak** [comment]
Hello @alerque -- we're currently looking into revamping this workflow.  Stay tuned for a better end-to-end process here.

**Comment by ylow** [comment]
This is in our runbook, and I believe the last few versions should be consistently tagged now. Closing this issue. Thanks!
