### ISSUE TITLE
Please update the Cargo.lock file before releases

### ISSUE THREAD

**Issue by alerque** [xetdata/xet-core#308]
I've been packaging releases for Arch Linux, and one thing we always try to do is create *reproducible* packages. That way anybody can verify that the binary artifacts in a release were indeed generated from the sources they were supposed to be. This also catches a lot of other problems with the build process.

One blocker for this project is that the Cargo.lock file is not getting updated properly. Ideally this this should be updated regularly during the development process, especially when any dependencies change in the Cargo.toml manifest or you want to pin new minor releases of dependencies. But **at the very least** it should be updated prior to tagging releases. That way the app can be built using `cargo build --locked` using a known-good set of dependency versions. This serves end users in case some dependency updates are inadvertently breaking, secures things in case of crate compromises, enables reproducible builds, etc.

Getting this done is pretty easy, just `cargo update` and commit the resulting `Cargo.lock` file. This should be done at a minimum after bumping the release version in `Cargo.toml`. It would probably be good to do it sometime shortly before the release, test with the pinned dependencies, then bump the version, then make sure the build runs with `cargo build --locked`.

CI should probably be adapted to run `--locked` too.

**Comment by ylow** [comment]
Currently we are not checking in the Cargo.lock files as per Rust guidance. Though it looks like the policy has changed lately. https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html 
I still don't have a clear understanding of the implications and what this means, will ask around and get back to you in a bit.

**Comment by alerque** [comment]
I think you've completely misunderstood the guidance, and it has not changed relative to this project. This project is not just a library, it is a whale app and ships several CLI binaries. The guidance on this scenario has *always* been to check in the lockfile. The only change is that the new guidance is that some pure-library crates should consider tracking lock files as well.

**Comment by hoytak** [comment]
In our release environment, it's a little more complicated as we have an internal build process that mirrors some of what you see here. This is due to the need for signing on the windows and OSX releases and building matching server-side libraries that pair with the client release components.  We want one Cargo.lock for this larger piece.  

To work with your request, however, we will separate out the git-xet program from the general xet-core workspace, and this part will have its own Cargo.lock file checked in to the environment.  Hopefully this will make the build process easier on your end.

**Comment by alerque** [comment]
No matter how complicated your build process and release sequence it shouldn't be hard to keep a lock file updated. The lock file is not linked to what build targets or build options or features or even platform is being used. It includes everything. Anywhere you run it `cargo update` should get the lock file in sync and then you can build anywhere with any options you like as long as the dependencies don't change versions. The same goes for `cargo fetch`, it fetches every dependency for every platform, even architectures you may not support at all. Then when a `cargo build --locked` happens no matter what the platform or target or build options the same lock file should be valid for everything.

All that to say I'm pretty confident you don't need to split anything into a separate workspace for this to get fixed without any downsides to any workflow you need. Even if you didn't want to do a locked build somewhere (which is a dubious need) you could still just not use `--locked` with no downside to *having* an up to date lock file for the whole workspace.

**Comment by alerque** [comment]
This has still not been properly addressed. The v0.14.3 release (and possibly others before it) does not build with locked deps because the lock file is out of date.

**Comment by hoytak** [comment]
I'm not sure what you are seeing.  Checking out the v0.14.3 tag and running cargo build in gitxet, libxet, and rust/ shows that all the committed Cargo.lock files are up to date.  Could you describe what your process is and what you're seeing is out of date?

**Comment by hoytak** [comment]
I'm not sure what you are seeing. Checking out the v0.14.3 tag from a clean directory and running cargo build in gitxet/ and libxet/ shows that both of the committed Cargo.lock files are up to date. Could you describe what your process is and what you're seeing is out of date?

**Comment by alerque** [comment]
I'm using the source tarball (`git archive` generated by GitHub) to download the tag, then switching to the `rust/` directory and running `cargo build --frozen --release`. You can't test this with `cargo build`, you need `cargo build --frozen`.

Historically that is where everything has been (`git-xet`, `xetcmd`, `xetmnt`), but it looks like `git-xet` moved to `gitxet/`. I don't know what `libxet` is yet in relation to the rest of the workspace.

**Comment by alerque** [comment]
v0.14.4 continued to manifest this problem. The *gitxet* builds okay with `--frozen`, but the stuff in *rust* does not and must be `cargo update`d before `cargo build --frozen` will run.
